### ISSUE TITLE
Add support for the KMM (Kotlin Multiplatform Mobile) project

### ISSUE THREAD

**Issue by suho** [infinum/kotlin-jsonapix#32]
## Why

The library currently does not support the KMM (Kotlin Multiplatform Mobile) project.

<img width="1841" alt="Surveys_–_build_gradle_kts___shared_" src="https://user-images.githubusercontent.com/19943832/190941463-c03ba372-a0be-46b5-b32a-b2071bd035d6.png">

Error:
<img width="1132" alt="Screen Shot 2022-09-19 at 09 36 49" src="https://user-images.githubusercontent.com/19943832/190941516-7874aa5a-f82f-4dd1-9b4f-1306996b2620.png">

 
## Who Benefits?

KMM Developers

Thanks

**Comment by stjepanbanek** [comment]
Hi @suho and thanks for your elaborate feedback.

Unfortunately, we have noticed the same issues with the lib in KMM projects, and the fix requires a significant amount of time. However, we do plan on supporting KMM in one of the future releases. Now, I can't tell exactly when that might happen due to high amount of work we have elsewhere. 

Rest assured that we will handle this in due time!
