### ISSUE TITLE
Mandatory to extends JsonApiModel even meta and links are not necessary

### ISSUE THREAD

**Issue by howardtamhk** [infinum/kotlin-jsonapix#60]
Thank you for the hard work to push the library to 1.0.0!! I find that after update to 1.0.0, if a data model doesn't extends `JsonApiModel`, it will return following error while building the app. 

```e: file:///.../com/infinum/jsonapix/JsonXExtensions.kt:130:88 Expression 'id' of type 'Int' cannot be invoked as a function. The function 'invoke()' is not found```

Is it mandatory to extends `JsonApiModel` starting from 1.0.0 even the model doesn't needs meta and links?

**Comment by thisAAY** [comment]
Hi Howard,

Appreciate your feedback! Since our last update, we've made several modifications. We're currently updating our README to reflect these changes. Please note that `JsonApiModel` now only includes `id` and `type`, while `meta` and `links` are part of the generated wrapper classes XModel and XList. Extending `id` and `type` is essential for the library's functionality.

I hope this clarifies your question. If you have any specific scenarios where extending JsonApiModel might be challenging, feel free to share, and we'll be happy to assist.

**Comment by howardtamhk** [comment]
Hi Ahmed,

Thank you for the prompt reply!. No, I don't see any issues to extend `JsonApiModel`. With the meta and links changes to `{foo}Model` , how can I get the meta data now?

**Comment by thisAAY** [comment]
You can check it under the breaking changes in the release notes [here](https://github.com/infinum/kotlin-jsonapix/releases/tag/1.0.0) 

But for asimple example if we take `Person` class

the lib will generate `PersonModel` and `PersonList` and these are the classes that you need to use with `TypeAdapter` and `Retrofit` too

and to get `meta` 

```kotlin
val personModel: PersonModel = apiService.fetchPerson()
val rootMeta = personModel.rootMeta
val resourceMeta = personModel.resourceObjectMeta

// For lists
val personList: PersonList = apiService.fetchPersonList()
val rootMeta = personList.rootMeta
val resourceMeta = personList.first().resourceObjectMeta // resource object meta of first item in the list
```

**Comment by thisAAY** [comment]
I will close this issue, if you have any more questions you can re-open it.
